### ISSUE TITLE
Not necessary to apply font-weight: bold on h2

### ISSUE THREAD

**Issue by jzhu01** [mrrichardasmith/prj-rev-bwfs-dasmoto#1]
Seen here: https://github.com/mrrichardasmith/prj-rev-bwfs-dasmoto/blob/master/DasmotoArtsCrafts/Resources/css/style.css#L9

Since the h2 is already bolded by default, this line doesn't affect the display.

**Comment by mrrichardasmith** [comment]
This makes sense. 
Thank You.
