### ISSUE TITLE
Nice job applying font-family once by selecting body

### ISSUE THREAD

**Issue by jzhu01** [mrrichardasmith/prj-rev-bwfs-dasmoto#2]
Seen here: https://github.com/mrrichardasmith/prj-rev-bwfs-dasmoto/blob/master/DasmotoArtsCrafts/Resources/css/style.css#L1-L4

Solid implementation. :)

**Comment by mrrichardasmith** [comment]
Thank You. I am pleased with the gaps in my knowledge plugged with this run through of specificity. It has definitely added a layer to knowledge.
