### ISSUE TITLE
Suggestion - instead of selecting span in CSS, select .price

### ISSUE THREAD

**Issue by jzhu01** [mrrichardasmith/prj-rev-bwfs-dasmoto#3]
Seen here: https://github.com/mrrichardasmith/prj-rev-bwfs-dasmoto/blob/master/DasmotoArtsCrafts/index.html#L17

You have a class defined, but instead you use span. Since span is more generic, I suggest switching to using .price instead.

**Comment by mrrichardasmith** [comment]
I think this must have been a moment of weakness. I put the class in the element and then didn't use it. Sloppy error on my part.

Thank You.
