### ISSUE TITLE
Nice job using IDs for h2s!

### ISSUE THREAD

**Issue by jzhu01** [mrrichardasmith/prj-rev-bwfs-dasmoto#4]
Seen here: https://github.com/mrrichardasmith/prj-rev-bwfs-dasmoto/blob/master/DasmotoArtsCrafts/index.html#L12

It's a really good choice, since each h2 is the same except for the background color, which is unique. :D

**Comment by mrrichardasmith** [comment]
Pleased that the extra time thinking about it sent me in the right direction. It doesn't always.
